name: oidc-lab
on: workflow_dispatch
permissions:
 id-token: write
 contents: read
jobs:
 assume-role:
   runs-on: ubuntu-latest
   steps:
     - name: Debug OIDC token claims
       run: |
         TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
           "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')
         echo $TOKEN | cut -d '.' -f2 | base64 -d 2>/dev/null | jq .
     - uses: aws-actions/configure-aws-credentials@v6
       with:
         role-to-assume: arn:aws:iam::006780474162:role/github-oidc-role
         aws-region: us-east-1
     - run: aws sts get-caller-identity
     - uses: actions/dependency-review-action@v4
     - name: Build image
       run: docker build -t myapp:${{ github.sha }} .
     - name: Scan container with Trivy
       uses: aquasecurity/trivy-action@master
       with:
         image-ref: 'myapp:${{ github.sha }}'
         format: 'sarif'
         output: 'trivy-container.sarif'
         severity: 'CRITICAL,HIGH'
     - name: Upload scan results
       uses: github/codeql-action/upload-sarif@v3
       with:
         sarif_file: 'trivy-container.sarif'
